/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

public class FormularioProductoCongelado extends javax.swing.JFrame {
    
    public FormularioProductoCongelado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        textAreaMostrar = new java.awt.TextArea();
        MetodCongela = new javax.swing.JLabel();
        PorAgua = new javax.swing.JButton();
        PorAire = new javax.swing.JButton();
        PorNitrógeno = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(480, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(102, 102, 102));
        Titulo.setFont(new java.awt.Font("LEMON MILK", 1, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Productos Congelados");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(102, 102, 102));
        btnCerrar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        textAreaMostrar.setVisible(false);
        getContentPane().add(textAreaMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 440, 510));

        MetodCongela.setBackground(new java.awt.Color(102, 102, 102));
        MetodCongela.setFont(new java.awt.Font("LEMON MILK", 0, 12)); // NOI18N
        MetodCongela.setForeground(new java.awt.Color(255, 255, 255));
        MetodCongela.setText("Metodo de Congelacion :");
        getContentPane().add(MetodCongela, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        PorAgua.setBackground(new java.awt.Color(102, 102, 102));
        PorAgua.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        PorAgua.setForeground(new java.awt.Color(255, 255, 255));
        PorAgua.setText("Por Agua");
        PorAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorAguaActionPerformed(evt);
            }
        });
        getContentPane().add(PorAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, 30));

        PorAire.setBackground(new java.awt.Color(102, 102, 102));
        PorAire.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        PorAire.setForeground(new java.awt.Color(255, 255, 255));
        PorAire.setText("Por Aire");
        PorAire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorAireActionPerformed(evt);
            }
        });
        getContentPane().add(PorAire, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 110, 30));

        PorNitrógeno.setBackground(new java.awt.Color(102, 102, 102));
        PorNitrógeno.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        PorNitrógeno.setForeground(new java.awt.Color(255, 255, 255));
        PorNitrógeno.setText("Por Nitrógeno");
        PorNitrógeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorNitrógenoActionPerformed(evt);
            }
        });
        getContentPane().add(PorNitrógeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/R (1).jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void PorAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorAguaActionPerformed
         FormularioCongeladoAgua formAgua = new FormularioCongeladoAgua();
    formAgua.setVisible(true);
    }//GEN-LAST:event_PorAguaActionPerformed

    private void PorAireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorAireActionPerformed
        FormularioCongeladoAire formAire = new FormularioCongeladoAire();
    formAire.setVisible(true);
    }//GEN-LAST:event_PorAireActionPerformed

    private void PorNitrógenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorNitrógenoActionPerformed
     FormularioCongeladoNitrógeno formNitrógeno = new FormularioCongeladoNitrógeno();
    formNitrógeno.setVisible(true);
    }//GEN-LAST:event_PorNitrógenoActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel MetodCongela;
    private javax.swing.JButton PorAgua;
    private javax.swing.JButton PorAire;
    private javax.swing.JButton PorNitrógeno;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCerrar;
    private java.awt.TextArea textAreaMostrar;
    // End of variables declaration//GEN-END:variables
}
